name: test workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deployment"
        required: true
        default: "dev-sandbox"
        type: choice
        options:
          - dev-sandbox
          - dev2
          - staging
          - production
          - dev

      version:
        description: "Select version to build"
        required: true
        default: "latest"
        type: choice
        options:
          - latest

jobs:
  call-workflow:
    uses: karthikeya-chinna/reusable-workflow/.github/workflows/main.yml@main
